### PR TITLE
Use "gray" not "grey" for American English example, run webpack

### LINKED ISSUE #9: Use "gray" in American English section
The example is "grey is my favorite color." It should be "gray is my favorite color," which is correctly converted if typed in.

### PR DESCRIPTION
**Pull request by nloveladyallen**
The main point of this PR was to fix #9, but webpack had a lot of other changes. Apparently people haven't been running it.

### CODE REVIEW

**Comment by spencermountain** [comment]
agh, thanks noah. sorry, should have seen this earlier.
hey, will you join the slack group? you're the best, and it's quickly-becoming a dream-team. 
superscript-slackin.herokuapp.com

**Comment by nloveladyallen** [comment]
Sorry, I don't use Slack. :/

**Comment by nloveladyallen** [comment]
Not to be pushy, but it's been over a week… Any chance of a merge?

**Comment by spencermountain** [comment]
hey, thanks for your patience. was out of town this week.
for future purposes, it looks like we're running different babel versions or something, so the diff is pretty big, that makes it a little scary, that's all.
done! thanks!

**Pull request merged**
